openapi: 3.0.3
info:
  title: Enduro API
  version: "1.0"
servers:
- url: http://localhost:9000
paths:
  /batch:
    get:
      tags:
      - batch
      summary: status batch
      description: Retrieve status of current batch operation.
      operationId: batch#status
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BatchStatusResult'
              example:
                run_id: Consequatur impedit vel exercitationem.
                running: true
                status: Ab nostrum consectetur.
                workflow_id: Quas at.
    post:
      tags:
      - batch
      summary: submit batch
      description: Submit a new batch
      operationId: batch#submit
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SubmitRequestBody'
            example:
              completed_dir: Et enim esse aut accusantium deleniti beatae.
              path: Iste ut alias et.
              retention_period: Molestiae in.
      responses:
        "202":
          description: Accepted response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BatchResult'
              example:
                run_id: Sed numquam.
                workflow_id: Sed distinctio dolorum et rerum non optio.
        "400":
          description: Bad Request response.
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                id: 3F1FKVRR
                message: Value of ID must be an integer
                name: bad_request
        "409":
          description: Conflict response.
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                id: 3F1FKVRR
                message: Value of ID must be an integer
                name: bad_request
  /batch/hints:
    get:
      tags:
      - batch
      summary: hints batch
      description: Retrieve form hints
      operationId: batch#hints
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BatchHintsResult'
              example:
                completed_dirs:
                - Commodi id.
                - Tempora eveniet eligendi.
                - Rem asperiores vero aliquid vel aut.
                - Quidem dicta nisi ipsum non illo id.
  /collection:
    get:
      tags:
      - collection
      summary: list collection
      description: List all stored collections
      operationId: collection#list
      parameters:
      - name: name
        in: query
        allowEmptyValue: true
        schema:
          type: string
          example: Nihil est est quo adipisci provident.
        example: Enim dolorem repellat et repellat.
      - name: aip_id
        in: query
        allowEmptyValue: true
        schema:
          type: string
          example: B140526E-56D0-0183-0B79-28E8969E1B3C
          format: uuid
        example: 3B15D937-70A4-0C6D-371A-A0BDAF451237
      - name: earliest_created_time
        in: query
        allowEmptyValue: true
        schema:
          type: string
          example: "2010-05-04T00:09:10Z"
          format: date-time
        example: "2010-05-14T08:00:12Z"
      - name: latest_created_time
        in: query
        allowEmptyValue: true
        schema:
          type: string
          example: "2012-09-24T02:46:57Z"
          format: date-time
        example: "2002-10-13T21:13:34Z"
      - name: status
        in: query
        allowEmptyValue: true
        schema:
          type: string
          example: error
          enum:
          - new
          - in progress
          - done
          - error
          - unknown
          - queued
          - pending
          - abandoned
        example: new
      - name: cursor
        in: query
        description: Pagination cursor
        allowEmptyValue: true
        schema:
          type: string
          description: Pagination cursor
          example: Ad ipsa.
        example: Eius fugiat laborum totam.
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListResponseBody'
              example:
                items:
                - aip_id: 288BFD74-D973-18B5-FAA5-29ADF4569AC7
                  completed_at: "1981-07-18T09:32:04Z"
                  created_at: "1983-12-07T23:41:35Z"
                  id: 2608592925037585396
                  name: Vitae illum magni placeat quo.
                  run_id: 3F59C655-AFF8-EAB8-FA17-44E154EF0557
                  started_at: "1998-03-18T12:36:31Z"
                  status: error
                  workflow_id: A464FD15-9F47-E3CC-BD80-3B5C5830C503
                - aip_id: 288BFD74-D973-18B5-FAA5-29ADF4569AC7
                  completed_at: "1981-07-18T09:32:04Z"
                  created_at: "1983-12-07T23:41:35Z"
                  id: 2608592925037585396
                  name: Vitae illum magni placeat quo.
                  run_id: 3F59C655-AFF8-EAB8-FA17-44E154EF0557
                  started_at: "1998-03-18T12:36:31Z"
                  status: error
                  workflow_id: A464FD15-9F47-E3CC-BD80-3B5C5830C503
                next_cursor: Facere cum.
  /collection/{id}:
    delete:
      tags:
      - collection
      summary: delete collection
      description: Delete collection by ID
      operationId: collection#delete
      parameters:
      - name: id
        in: path
        description: Identifier of collection to delete
        required: true
        schema:
          type: integer
          description: Identifier of collection to delete
          example: 7638789534826980623
        example: 11003716713769220718
      responses:
        "204":
          description: No Content response.
        "404":
          description: Not Found response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CollectionNotfound'
              example:
                id: 2165236649375698924
                message: Sit ea et et dolor.
    get:
      tags:
      - collection
      summary: show collection
      description: Show collection by ID
      operationId: collection#show
      parameters:
      - name: id
        in: path
        description: Identifier of collection to show
        required: true
        schema:
          type: integer
          description: Identifier of collection to show
          example: 11427972956700943101
        example: 9203513792022244598
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EnduroStoredCollection'
              example:
                aip_id: 2AE5027E-EF4C-E00D-314E-1CB4449A11C0
                completed_at: "1997-08-27T00:00:04Z"
                created_at: "1989-09-24T08:53:28Z"
                id: 3703921289856403029
                name: Ut alias voluptas molestias et quia sit.
                run_id: 77DFBD55-EC3C-CF64-7021-5A80D932517B
                started_at: "1998-02-12T04:24:46Z"
                status: error
                workflow_id: 0E0CB887-B526-812D-F285-DE018C555BB8
        "404":
          description: Not Found response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CollectionNotfound'
              example:
                id: 2246475217907625301
                message: Ea tenetur deleniti vel.
  /collection/{id}/cancel:
    post:
      tags:
      - collection
      summary: cancel collection
      description: Cancel collection processing by ID
      operationId: collection#cancel
      parameters:
      - name: id
        in: path
        description: Identifier of collection to remove
        required: true
        schema:
          type: integer
          description: Identifier of collection to remove
          example: 11753811572662635557
        example: 14930879189291518875
      responses:
        "200":
          description: OK response.
        "400":
          description: Bad Request response.
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                id: 3F1FKVRR
                message: Value of ID must be an integer
                name: bad_request
        "404":
          description: Not Found response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CollectionNotfound'
              example:
                id: 3508348661133018630
                message: Explicabo nam praesentium iste et aliquid.
  /collection/{id}/download:
    get:
      tags:
      - collection
      summary: download collection
      description: Download collection by ID
      operationId: collection#download
      parameters:
      - name: id
        in: path
        description: Identifier of collection to look up
        required: true
        schema:
          type: integer
          description: Identifier of collection to look up
          example: 17298149395404699584
        example: 7494586481663086822
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                type: string
                example:
                - 83
                - 117
                - 115
                - 99
                - 105
                - 112
                - 105
                - 116
                - 32
                - 115
                - 97
                - 101
                - 112
                - 101
                - 32
                - 114
                - 101
                - 112
                - 117
                - 100
                - 105
                - 97
                - 110
                - 100
                - 97
                - 101
                - 32
                - 112
                - 114
                - 97
                - 101
                - 115
                - 101
                - 110
                - 116
                - 105
                - 117
                - 109
                - 32
                - 113
                - 117
                - 105
                - 97
                - 32
                - 109
                - 111
                - 108
                - 101
                - 115
                - 116
                - 105
                - 97
                - 101
                - 32
                - 118
                - 111
                - 108
                - 117
                - 112
                - 116
                - 97
                - 116
                - 101
                - 109
                - 46
                format: binary
              example:
              - 84
              - 101
              - 109
              - 112
              - 111
              - 114
              - 97
              - 32
              - 101
              - 110
              - 105
              - 109
              - 46
        "404":
          description: Not Found response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CollectionNotfound'
              example:
                id: 11956141247744386323
                message: Sed possimus voluptatum.
  /collection/{id}/preservation-actions:
    get:
      tags:
      - collection
      summary: preservation-actions collection
      description: List all preservation actions by ID
      operationId: collection#preservation-actions
      parameters:
      - name: id
        in: path
        description: Identifier of collection to look up
        required: true
        schema:
          type: integer
          description: Identifier of collection to look up
          example: 11875688747252261123
        example: 6801610311019669209
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EnduroCollectionPreservationActions'
              example:
                actions:
                - action_id: Veritatis cumque.
                  id: 17014779284437445999
                  name: Quod impedit sapiente ea.
                  started_at: "2015-08-09T01:52:06Z"
                  status: processing
                - action_id: Veritatis cumque.
                  id: 17014779284437445999
                  name: Quod impedit sapiente ea.
                  started_at: "2015-08-09T01:52:06Z"
                  status: processing
                - action_id: Veritatis cumque.
                  id: 17014779284437445999
                  name: Quod impedit sapiente ea.
                  started_at: "2015-08-09T01:52:06Z"
                  status: processing
                - action_id: Veritatis cumque.
                  id: 17014779284437445999
                  name: Quod impedit sapiente ea.
                  started_at: "2015-08-09T01:52:06Z"
                  status: processing
        "404":
          description: Not Found response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CollectionNotfound'
              example:
                id: 13124819927299222419
                message: Et rem ducimus iste maiores.
  /collection/{id}/retry:
    post:
      tags:
      - collection
      summary: retry collection
      description: Retry collection processing by ID
      operationId: collection#retry
      parameters:
      - name: id
        in: path
        description: Identifier of collection to retry
        required: true
        schema:
          type: integer
          description: Identifier of collection to retry
          example: 13928084075125878608
        example: 1459351663664876143
      responses:
        "200":
          description: OK response.
        "400":
          description: Bad Request response.
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                id: 3F1FKVRR
                message: Value of ID must be an integer
                name: bad_request
        "404":
          description: Not Found response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CollectionNotfound'
              example:
                id: 12367619642138472932
                message: Quae est debitis.
  /collection/{id}/workflow:
    get:
      tags:
      - collection
      summary: workflow collection
      description: Retrieve workflow status by ID
      operationId: collection#workflow
      parameters:
      - name: id
        in: path
        description: Identifier of collection to look up
        required: true
        schema:
          type: integer
          description: Identifier of collection to look up
          example: 14235750693972130264
        example: 4501196470416696206
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EnduroCollectionWorkflowStatus'
              example:
                history:
                - details: Ut reprehenderit eos consequuntur iusto.
                  id: 8869941666368485627
                  type: Amet rerum quam sequi.
                - details: Ut reprehenderit eos consequuntur iusto.
                  id: 8869941666368485627
                  type: Amet rerum quam sequi.
                status: Vitae laudantium sunt ad.
        "404":
          description: Not Found response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CollectionNotfound'
              example:
                id: 2843051066282331256
                message: Velit sint aut veritatis ut quo rerum.
  /collection/bulk:
    get:
      tags:
      - collection
      summary: bulk_status collection
      description: Retrieve status of current bulk operation.
      operationId: collection#bulk_status
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BulkStatusResult'
              example:
                closed_at: "1998-12-23T17:12:34Z"
                run_id: Voluptatem ab similique aut sed velit ad.
                running: false
                started_at: "1986-02-24T20:28:38Z"
                status: Amet sint autem.
                workflow_id: Eveniet atque ipsum esse.
    post:
      tags:
      - collection
      summary: bulk collection
      description: Bulk operations (retry, cancel...).
      operationId: collection#bulk
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BulkRequestBody'
            example:
              operation: cancel
              size: 3764210318943693810
              status: in progress
      responses:
        "202":
          description: Accepted response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BatchResult'
              example:
                run_id: Et consequatur eum eligendi est aspernatur.
                workflow_id: Expedita sunt quas aut qui nostrum illo.
        "400":
          description: Bad Request response.
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                id: 3F1FKVRR
                message: Value of ID must be an integer
                name: bad_request
        "409":
          description: Conflict response.
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                id: 3F1FKVRR
                message: Value of ID must be an integer
                name: bad_request
  /collection/monitor:
    get:
      tags:
      - collection
      summary: monitor collection
      operationId: collection#monitor
      responses:
        "101":
          description: Switching Protocols response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EnduroMonitorUpdate'
              example:
                id: 10035519767337458041
                item:
                  aip_id: 288BFD74-D973-18B5-FAA5-29ADF4569AC7
                  completed_at: "1981-07-18T09:32:04Z"
                  created_at: "1983-12-07T23:41:35Z"
                  id: 2608592925037585396
                  name: Vitae illum magni placeat quo.
                  run_id: 3F59C655-AFF8-EAB8-FA17-44E154EF0557
                  started_at: "1998-03-18T12:36:31Z"
                  status: error
                  workflow_id: A464FD15-9F47-E3CC-BD80-3B5C5830C503
                type: Laboriosam odit.
  /swagger/swagger.json:
    get:
      tags:
      - swagger
      summary: Download internal/api/gen/http/openapi.json
      description: JSON document containing the API swagger definition.
      operationId: swagger#/swagger/swagger.json
      responses:
        "200":
          description: File downloaded
components:
  schemas:
    BatchHintsResult:
      type: object
      properties:
        completed_dirs:
          type: array
          items:
            type: string
            example: Atque voluptatem incidunt doloremque cum.
          description: A list of known values of completedDir used by existing watchers.
          example:
          - Odio non laborum dolores voluptatem cum in.
          - Aliquid non tempore vel in.
          - Cupiditate ipsam omnis voluptatem cum.
      example:
        completed_dirs:
        - Error adipisci vel rerum quo odit.
        - Numquam totam est nobis aspernatur voluptatibus quo.
    BatchResult:
      type: object
      properties:
        run_id:
          type: string
          example: Laborum harum dolor.
        workflow_id:
          type: string
          example: Numquam nam commodi et veniam.
      example:
        run_id: Tempora maxime fuga dolorem repudiandae et.
        workflow_id: Qui esse.
      required:
      - workflow_id
      - run_id
    BatchStatusResult:
      type: object
      properties:
        run_id:
          type: string
          example: Voluptas quas incidunt.
        running:
          type: boolean
          example: true
        status:
          type: string
          example: Sint maiores labore minus.
        workflow_id:
          type: string
          example: Ipsa blanditiis.
      example:
        run_id: Nam vitae autem labore esse aut.
        running: true
        status: Nisi repellendus qui.
        workflow_id: Sed commodi vel tenetur.
      required:
      - running
    BulkRequestBody:
      type: object
      properties:
        operation:
          type: string
          example: retry
          enum:
          - retry
          - cancel
          - abandon
        size:
          type: integer
          default: 100
          example: 14589513498438080383
        status:
          type: string
          example: new
          enum:
          - new
          - in progress
          - done
          - error
          - unknown
          - queued
          - pending
          - abandoned
      example:
        operation: cancel
        size: 17865545636725661851
        status: done
      required:
      - operation
      - status
    BulkStatusResult:
      type: object
      properties:
        closed_at:
          type: string
          example: "1998-11-15T13:24:26Z"
          format: date-time
        run_id:
          type: string
          example: Dicta culpa id dolorem.
        running:
          type: boolean
          example: false
        started_at:
          type: string
          example: "1987-02-13T19:42:16Z"
          format: date-time
        status:
          type: string
          example: Ipsa dolor deserunt provident provident.
        workflow_id:
          type: string
          example: Voluptatem exercitationem atque quo impedit.
      example:
        closed_at: "1992-06-05T21:46:04Z"
        run_id: Natus a sed nam.
        running: true
        started_at: "1997-11-10T23:06:37Z"
        status: Nisi recusandae est autem et expedita distinctio.
        workflow_id: Et est tenetur vel.
      required:
      - running
    CollectionNotfound:
      type: object
      properties:
        id:
          type: integer
          description: Identifier of missing collection
          example: 3597486707360869379
        message:
          type: string
          description: Message of error
          example: Aliquam aut.
      description: Collection not found
      example:
        id: 656191046410806374
        message: Ducimus velit perferendis ut dolorem qui.
      required:
      - message
      - id
    EnduroCollectionPreservationActions:
      type: object
      properties:
        actions:
          $ref: '#/components/schemas/EnduroCollectionPreservationActionsActionCollection'
      example:
        actions:
        - action_id: Veritatis cumque.
          id: 17014779284437445999
          name: Quod impedit sapiente ea.
          started_at: "2015-08-09T01:52:06Z"
          status: processing
        - action_id: Veritatis cumque.
          id: 17014779284437445999
          name: Quod impedit sapiente ea.
          started_at: "2015-08-09T01:52:06Z"
          status: processing
        - action_id: Veritatis cumque.
          id: 17014779284437445999
          name: Quod impedit sapiente ea.
          started_at: "2015-08-09T01:52:06Z"
          status: processing
        - action_id: Veritatis cumque.
          id: 17014779284437445999
          name: Quod impedit sapiente ea.
          started_at: "2015-08-09T01:52:06Z"
          status: processing
    EnduroCollectionPreservationActionsAction:
      type: object
      properties:
        action_id:
          type: string
          example: Eveniet dignissimos accusamus distinctio.
        id:
          type: integer
          example: 11110368612113983358
        name:
          type: string
          example: Qui quidem nemo quia dolor ea ullam.
        started_at:
          type: string
          example: "2012-04-17T22:45:46Z"
          format: date-time
        status:
          type: string
          example: unspecified
          enum:
          - unspecified
          - complete
          - processing
          - failed
      description: PreservationAction describes a preservation action.
      example:
        action_id: Dignissimos similique quisquam.
        id: 9528636745116951897
        name: Libero dolorem libero neque.
        started_at: "2007-11-13T23:58:40Z"
        status: unspecified
      required:
      - id
      - action_id
      - name
      - status
      - started_at
    EnduroCollectionPreservationActionsActionCollection:
      type: array
      items:
        $ref: '#/components/schemas/EnduroCollectionPreservationActionsAction'
      example:
      - action_id: Veritatis cumque.
        id: 17014779284437445999
        name: Quod impedit sapiente ea.
        started_at: "2015-08-09T01:52:06Z"
        status: processing
      - action_id: Veritatis cumque.
        id: 17014779284437445999
        name: Quod impedit sapiente ea.
        started_at: "2015-08-09T01:52:06Z"
        status: processing
    EnduroCollectionWorkflowHistory:
      type: object
      properties:
        details:
          type: string
          description: Contents of the event
          example: Et culpa eum non.
          format: binary
        id:
          type: integer
          description: Identifier of collection
          example: 2810303458441790849
        type:
          type: string
          description: Type of the event
          example: Ducimus omnis ea.
      description: WorkflowHistoryEvent describes a history event in Temporal.
      example:
        details: Officiis ea assumenda incidunt occaecati qui.
        id: 4728556995103678722
        type: Sint repellat laudantium ut vel corporis.
    EnduroCollectionWorkflowHistoryCollection:
      type: array
      items:
        $ref: '#/components/schemas/EnduroCollectionWorkflowHistory'
      example:
      - details: Ut reprehenderit eos consequuntur iusto.
        id: 8869941666368485627
        type: Amet rerum quam sequi.
      - details: Ut reprehenderit eos consequuntur iusto.
        id: 8869941666368485627
        type: Amet rerum quam sequi.
      - details: Ut reprehenderit eos consequuntur iusto.
        id: 8869941666368485627
        type: Amet rerum quam sequi.
      - details: Ut reprehenderit eos consequuntur iusto.
        id: 8869941666368485627
        type: Amet rerum quam sequi.
    EnduroCollectionWorkflowStatus:
      type: object
      properties:
        history:
          $ref: '#/components/schemas/EnduroCollectionWorkflowHistoryCollection'
        status:
          type: string
          example: Ab voluptas commodi omnis.
      example:
        history:
        - details: Ut reprehenderit eos consequuntur iusto.
          id: 8869941666368485627
          type: Amet rerum quam sequi.
        - details: Ut reprehenderit eos consequuntur iusto.
          id: 8869941666368485627
          type: Amet rerum quam sequi.
        status: Vel sint illo sunt.
    EnduroMonitorUpdate:
      type: object
      properties:
        id:
          type: integer
          description: Identifier of collection
          example: 16279269383789341971
        item:
          $ref: '#/components/schemas/EnduroStoredCollection'
        type:
          type: string
          description: Type of the event
          example: Vel sunt.
      example:
        id: 3365661111003968594
        item:
          aip_id: 288BFD74-D973-18B5-FAA5-29ADF4569AC7
          completed_at: "1981-07-18T09:32:04Z"
          created_at: "1983-12-07T23:41:35Z"
          id: 2608592925037585396
          name: Vitae illum magni placeat quo.
          run_id: 3F59C655-AFF8-EAB8-FA17-44E154EF0557
          started_at: "1998-03-18T12:36:31Z"
          status: error
          workflow_id: A464FD15-9F47-E3CC-BD80-3B5C5830C503
        type: Consequuntur laborum deserunt sapiente blanditiis laudantium.
      required:
      - id
      - type
    EnduroStoredCollection:
      type: object
      properties:
        aip_id:
          type: string
          description: Identifier of Archivematica AIP
          example: AF3C2FF8-1A90-BD97-39C4-B4426C5778CC
          format: uuid
        completed_at:
          type: string
          description: Completion datetime
          example: "1976-04-04T20:53:45Z"
          format: date-time
        created_at:
          type: string
          description: Creation datetime
          example: "1980-08-23T04:12:55Z"
          format: date-time
        id:
          type: integer
          description: Identifier of collection
          example: 356243881726260884
        name:
          type: string
          description: Name of the collection
          example: Beatae tenetur sed.
        run_id:
          type: string
          description: Identifier of latest processing workflow run
          example: 38F93803-BFA0-82D1-0649-B0769F6F7519
          format: uuid
        started_at:
          type: string
          description: Start datetime
          example: "1979-07-05T10:19:35Z"
          format: date-time
        status:
          type: string
          description: Status of the collection
          default: new
          example: new
          enum:
          - new
          - in progress
          - done
          - error
          - unknown
          - queued
          - pending
          - abandoned
        workflow_id:
          type: string
          description: Identifier of processing workflow
          example: 86EDFB6E-94F4-2B51-2B7E-E4683F848FD6
          format: uuid
      description: StoredCollection describes a collection retrieved by the service.
      example:
        aip_id: 34287C80-E47A-5C59-54F8-1AC4DAC80AFD
        completed_at: "1994-06-22T02:02:01Z"
        created_at: "1970-09-22T08:16:12Z"
        id: 4617371094919314860
        name: Ut aut error ut.
        run_id: EF5D214E-555E-4D58-0EF2-F45C1076AF15
        started_at: "1976-12-14T17:47:13Z"
        status: new
        workflow_id: 1883B2DF-F70A-5DB7-7F4C-C27752CD3BFF
      required:
      - id
      - status
      - created_at
    EnduroStoredCollectionCollection:
      type: array
      items:
        $ref: '#/components/schemas/EnduroStoredCollection'
      example:
      - aip_id: 288BFD74-D973-18B5-FAA5-29ADF4569AC7
        completed_at: "1981-07-18T09:32:04Z"
        created_at: "1983-12-07T23:41:35Z"
        id: 2608592925037585396
        name: Vitae illum magni placeat quo.
        run_id: 3F59C655-AFF8-EAB8-FA17-44E154EF0557
        started_at: "1998-03-18T12:36:31Z"
        status: error
        workflow_id: A464FD15-9F47-E3CC-BD80-3B5C5830C503
      - aip_id: 288BFD74-D973-18B5-FAA5-29ADF4569AC7
        completed_at: "1981-07-18T09:32:04Z"
        created_at: "1983-12-07T23:41:35Z"
        id: 2608592925037585396
        name: Vitae illum magni placeat quo.
        run_id: 3F59C655-AFF8-EAB8-FA17-44E154EF0557
        started_at: "1998-03-18T12:36:31Z"
        status: error
        workflow_id: A464FD15-9F47-E3CC-BD80-3B5C5830C503
    Error:
      type: object
      properties:
        fault:
          type: boolean
          description: Is the error a server-side fault?
          example: true
        id:
          type: string
          description: ID is a unique identifier for this particular occurrence of
            the problem.
          example: 123abc
        message:
          type: string
          description: Message is a human-readable explanation specific to this occurrence
            of the problem.
          example: parameter 'p' must be an integer
        name:
          type: string
          description: Name is the name of this class of errors.
          example: bad_request
        temporary:
          type: boolean
          description: Is the error temporary?
          example: true
        timeout:
          type: boolean
          description: Is the error a timeout?
          example: true
      example:
        id: 3F1FKVRR
        message: Value of ID must be an integer
        name: bad_request
      required:
      - name
      - id
      - message
      - temporary
      - timeout
      - fault
    ListResponseBody:
      type: object
      properties:
        items:
          $ref: '#/components/schemas/EnduroStoredCollectionCollection'
        next_cursor:
          type: string
          example: Et voluptas ullam.
      example:
        items:
        - aip_id: 288BFD74-D973-18B5-FAA5-29ADF4569AC7
          completed_at: "1981-07-18T09:32:04Z"
          created_at: "1983-12-07T23:41:35Z"
          id: 2608592925037585396
          name: Vitae illum magni placeat quo.
          run_id: 3F59C655-AFF8-EAB8-FA17-44E154EF0557
          started_at: "1998-03-18T12:36:31Z"
          status: error
          workflow_id: A464FD15-9F47-E3CC-BD80-3B5C5830C503
        - aip_id: 288BFD74-D973-18B5-FAA5-29ADF4569AC7
          completed_at: "1981-07-18T09:32:04Z"
          created_at: "1983-12-07T23:41:35Z"
          id: 2608592925037585396
          name: Vitae illum magni placeat quo.
          run_id: 3F59C655-AFF8-EAB8-FA17-44E154EF0557
          started_at: "1998-03-18T12:36:31Z"
          status: error
          workflow_id: A464FD15-9F47-E3CC-BD80-3B5C5830C503
        next_cursor: Ea accusantium velit dolores aut et sint.
      required:
      - items
    SubmitRequestBody:
      type: object
      properties:
        completed_dir:
          type: string
          example: Sint provident eum odit ut perspiciatis quis.
        path:
          type: string
          example: Dolorum minus.
        retention_period:
          type: string
          example: Adipisci reprehenderit accusamus exercitationem minima.
      example:
        completed_dir: Consectetur molestiae consectetur veniam vel aliquid eligendi.
        path: Quae recusandae aperiam ullam vitae quas quia.
        retention_period: Repellendus modi saepe.
      required:
      - path
tags:
- name: batch
  description: The batch service manages batches of collections.
- name: collection
  description: The collection service manages packages being transferred to Archivematica.
- name: swagger
  description: The swagger service serves the API swagger definition.
